[package]
name = "j8tw"
version = "0.1.0"
authors = ["Evan Martin <evan.martin@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
j8t = { path = "../" }
serde = "^1.0.59"
serde_derive = "^1.0.59"

[dependencies.wasm-bindgen]
version = "^0.2"
features = ["serde-serialize"]
